#if !defined(AFX_MYACTIVEX_H__CF04B61C_84F7_44DF_881C_0C8BC25B9D6C__INCLUDED_)
#define AFX_MYACTIVEX_H__CF04B61C_84F7_44DF_881C_0C8BC25B9D6C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMyActiveX wrapper class

class CMyActiveX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMyActiveX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbf4c592b, 0x6856, 0x4c01, { 0x90, 0xb8, 0x75, 0xb8, 0x15, 0x5f, 0x5d, 0x96 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	long GetLineWidth();
	void SetLineWidth(long);
	long GetCycle();
	void SetCycle(long);

// Operations
public:
	void Animate();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MYACTIVEX_H__CF04B61C_84F7_44DF_881C_0C8BC25B9D6C__INCLUDED_)
